---
version: '3'

services:

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.development
    ports:
      - "10200:4200"
    environment:
        API_BASE_URL: 'http://localhost:10880/api/'
    volumes:
      - .:/app
    tty: true
