FROM node:12.20.0

RUN mkdir /app
WORKDIR /app

ADD . .

#yarn init
#yarn add @angular/cli
#yarn add @angular/cdk
#yarn add @angular/material
#node_modules/.bin/ng new invest-app
#node_modules/.bin/ng serve --host 0.0.0.0

